#!/usr/bin/env bash

DIFFLISTPATH="${HOME}/.altPkgControl"
FEXT="alist"

HELP="Usage: $0 command parameter

Commands include:
  help - display usage [No param]
  list - list DPKG-installed packages [No param]
  pkgc - list number of DPKG-installed packages [No param]
  inst - installs DPKG package [Package name]
  rem - purges DPKG package [Package name]
  up - update the DPKG package list AND upgrade DPKG packages [No param]
  llist - list packagelists [No param]
  ldel - remove a packagelist without purging DPKG package(s) [Package name]
"

# Lock
if [[ -f "${DIFFLISTPATH}/lock" ]]; then
	echo "Process already running."
	exit 1
fi
touch "${DIFFLISTPATH}/lock"

unlock(){
	rm "${DIFFLISTPATH}/lock"
}
trap unlock EXIT


dircheck(){
	if ! [[ -d "${DIFFLISTPATH}" ]]; then
		mkdir ${DIFFLISTPATH}
	fi
}

paramcheck(){
	if [[ -z $1 ]]; then
		echo "No param specified"
		exit 1
	fi
}


if [[ $# -le 0 ]]; then
	echo "$HELP"
	exit 0
fi

while (( $# > 0 ))
do
	cmd="$1"
	case $cmd in
		help)
			echo "$HELP"
			exit 0
			;;
		list)
			LISTSTR=$(dpkg-query -W -f='${binary:Package}/${Version}\n')
			echo "$LISTSTR"
			;;
		pkgc)
			echo $(dpkg -l | grep -c "^ii")
			exit 0
			;;
		inst)
			shift
			paramcheck "$1"
			dircheck
			OUTFILE=${DIFFLISTPATH}/$1.${FEXT}
			if [[ -f "${OUTFILE}" ]]; then
				read -p "Package list '$1' already exists, overwrite it? [y/N] " yn
					case $yn in
						[yY])
							echo "Overwritting $1's package list..."
							;;
						*)
							exit 0
							;;
					esac
			fi

			PREFILE="${DIFFLISTPATH}/PRE$1.${FEXT}"
			PREPKGS=$(dpkg-query -W -f='${binary:Package}\n')
			echo "${PREPKGS}" > "${PREFILE}"

			echo "You may want to enter 'y' after confirming sudo."
			INSTALLSTR=$(sudo apt install $1)

			POSTFILE="${DIFFLISTPATH}/POST$1.${FEXT}"
			POSTPKGS=$(dpkg-query -W -f='${binary:Package}\n')
			echo "${POSTPKGS}" > "${POSTFILE}"

			echo -e "$INSTALLSTR"

			DIFFPKGS=$(diff "${PREFILE}" "${POSTFILE}" | grep -o ">.*" | sed "s/>\s//" | sed "s/:.*//")



			echo "${DIFFPKGS}" > "${OUTFILE}"
			rm "${PREFILE}"
			rm "${POSTFILE}"
			exit 0
			;;
		rem)
			shift
			paramcheck "$1"
			dircheck
			OUTFILE=${DIFFLISTPATH}/$1.${FEXT}
			if ! [[ -f "${OUTFILE}" ]]; then
				read -p "Package list '$1' does not exist. Attempt to purge package anyway? [y/N] " yn
					case $yn in
						[yY])
							echo "Attempting to purge $1..."
								sudo apt remove --purge $1
								sudo apt autoremove --purge
							exit 0
							;;
						*)
							exit 0
							;;
					esac
			fi

			LISTFILE="$(cat "${OUTFILE}" | tr '\n' ' ')"
			sudo apt remove --purge ${LISTFILE}
			sudo apt autoremove --purge
			rm "${OUTFILE}"
			exit 0
			;;
		up)
			sudo apt update
			sudo apt upgrade
			exit 0
			;;
		llist)
			ls -1 "${DIFFLISTPATH}" | grep -Eo ".*\.alist" | sed -E "s/\.alist//g"
			exit 0
			;;
		ldel)
			shift
			paramcheck "$1"
			dircheck
			OUTFILE="${DIFFLISTPATH}/$1.${FEXT}"
			if ! [[ -f "${OUTFILE}" ]]; then
				echo "Package list '$1' does not exist."
				exit 1
			fi

			rm "${OUTFILE}"
			echo "Deleted '$1'"
			exit 0
			;;
		*)
			echo "Unknown command: '$cmd'" >&2
			exit 1
			;;
	esac
	shift
done
